import { NextRequest, NextResponse } from "next/server";

const bookings = [
  {
    id: "BK-001",
    customerId: "CU-01",
    customerName: "Rahim Uddin",
    customerPhone: "+880 1711-234567",
    groundId: "GR-01",
    groundName: "Green Arena",
    date: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    startTime: "10:00",
    endTime: "11:00",
    duration: 1,
    amount: 1200,
    status: "confirmed",
    paymentStatus: "paid",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "BK-002",
    customerId: "CU-02",
    customerName: "Karim Hossain",
    customerPhone: "+880 1812-345678",
    groundId: "GR-02",
    groundName: "Blue Pitch",
    date: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    startTime: "13:00",
    endTime: "15:00",
    duration: 2,
    amount: 2400,
    status: "pending",
    paymentStatus: "pending",
    notes: "Needs extra seating",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "BK-003",
    customerId: "CU-03",
    customerName: "Nasrin Akter",
    customerPhone: "+880 1913-456789",
    groundId: "GR-03",
    groundName: "Red Court",
    date: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    startTime: "16:00",
    endTime: "17:00",
    duration: 1,
    amount: 900,
    status: "confirmed",
    paymentStatus: "paid",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "BK-004",
    customerId: "CU-04",
    customerName: "Salam Sheikh",
    customerPhone: "+880 1614-567890",
    groundId: "GR-01",
    groundName: "Green Arena",
    date: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    startTime: "19:00",
    endTime: "21:00",
    duration: 2,
    amount: 2400,
    status: "confirmed",
    paymentStatus: "paid",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "BK-005",
    customerId: "CU-05",
    customerName: "Farida Begum",
    customerPhone: "+880 1515-678901",
    groundId: "GR-04",
    groundName: "Gold Tennis",
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    startTime: "08:00",
    endTime: "09:00",
    duration: 1,
    amount: 900,
    status: "cancelled",
    paymentStatus: "refunded",
    notes: "Customer cancelled",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "BK-006",
    customerId: "CU-06",
    customerName: "Jahangir Alam",
    customerPhone: "+880 1716-789012",
    groundId: "GR-02",
    groundName: "Blue Pitch",
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    startTime: "14:00",
    endTime: "16:00",
    duration: 2,
    amount: 3600,
    status: "completed",
    paymentStatus: "paid",
    notes: "",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "BK-007",
    customerId: "CU-07",
    customerName: "Hasib Rahman",
    customerPhone: "+880 1717-890123",
    groundId: "GR-01",
    groundName: "Green Arena",
    date: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
    startTime: "14:00",
    endTime: "15:00",
    duration: 1,
    amount: 1200,
    status: "pending",
    paymentStatus: "pending",
    notes: "Birthday party — need extra chairs and a PA system",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "BK-008",
    customerId: "CU-08",
    customerName: "Mitu Akter",
    customerPhone: "+880 1918-901234",
    groundId: "GR-03",
    groundName: "Red Court",
    date: new Date(Date.now() + 50 * 60 * 60 * 1000).toISOString(),
    startTime: "17:00",
    endTime: "18:00",
    duration: 1,
    amount: 600,
    status: "pending",
    paymentStatus: "partial",
    notes: "",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "BK-009",
    customerId: "CU-09",
    customerName: "Rony Mia",
    customerPhone: "+880 1619-012345",
    groundId: "GR-04",
    groundName: "Gold Tennis",
    date: new Date(Date.now() + 28 * 60 * 60 * 1000).toISOString(),
    startTime: "09:00",
    endTime: "10:00",
    duration: 1,
    amount: 900,
    status: "pending",
    paymentStatus: "paid",
    notes: "First-time customer referred by Rahim Uddin",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "BK-010",
    customerId: "CU-10",
    customerName: "Shakib Hasan",
    customerPhone: "+880 1820-123456",
    groundId: "GR-02",
    groundName: "Blue Pitch",
    date: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
    startTime: "11:00",
    endTime: "13:00",
    duration: 2,
    amount: 3600,
    status: "pending",
    paymentStatus: "pending",
    notes: "Corporate tournament — 20 players, require scoreboard",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

export async function GET() {
  return NextResponse.json({ success: true, data: bookings });
}

export async function POST(req: NextRequest) {
  const body = await req.json();
  const newBooking = {
    id: `BK-${String(bookings.length + 1).padStart(3, "0")}`,
    ...body,
    status: body.status ?? "confirmed",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  bookings.push(newBooking);
  return NextResponse.json({ success: true, data: newBooking }, { status: 201 });
}
