import { NextResponse } from "next/server";

const details: Record<string, object> = {
  "BK-001": {
    id: "BK-001",
    customerId: "CU-01",
    customerName: "Rahim Uddin",
    customerPhone: "+880 1711-234567",
    customerEmail: "rahim.uddin@example.com",
    customerTotalBookings: 14,
    groundId: "GR-01",
    groundName: "Green Arena",
    groundType: "football",
    groundCapacity: 22,
    groundOpeningTime: "06:00",
    groundClosingTime: "23:00",
    groundIsActive: true,
    date: new Date(Date.now() + 1 * 60 * 60 * 1000).toISOString(),
    startTime: "10:00",
    endTime: "11:00",
    duration: 1,
    pricePerHour: 1200,
    amount: 1200,
    status: "confirmed",
    paymentStatus: "paid",
    paymentMethod: "card",
    cardLast4: "4242",
    stripeTransactionId: "pi_3PqA1RLkdIwHu7ix0QMHBFR2",
    notes: "",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { event: "Booking created", timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString() },
      { event: "Confirmation email sent", timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000 + 30000).toISOString() },
      { event: "Payment completed", timestamp: new Date(Date.now() - 1.9 * 60 * 60 * 1000).toISOString() },
      { event: "Booking confirmed", timestamp: new Date(Date.now() - 1.8 * 60 * 60 * 1000).toISOString() },
    ],
  },
  "BK-002": {
    id: "BK-002",
    customerId: "CU-02",
    customerName: "Karim Hossain",
    customerPhone: "+880 1812-345678",
    customerEmail: "karim.hossain@example.com",
    customerTotalBookings: 3,
    groundId: "GR-02",
    groundName: "Blue Pitch",
    groundType: "cricket",
    groundCapacity: 30,
    groundOpeningTime: "07:00",
    groundClosingTime: "22:00",
    groundIsActive: true,
    date: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    startTime: "13:00",
    endTime: "15:00",
    duration: 2,
    pricePerHour: 1200,
    amount: 2400,
    status: "pending",
    paymentStatus: "pending",
    paymentMethod: "upi",
    cardLast4: null,
    stripeTransactionId: null,
    notes: "Needs extra seating",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    timeline: [
      { event: "Booking created", timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
      { event: "Confirmation email sent", timestamp: new Date(Date.now() - 29 * 60 * 1000).toISOString() },
    ],
  },
  "BK-003": {
    id: "BK-003",
    customerId: "CU-03",
    customerName: "Nasrin Akter",
    customerPhone: "+880 1913-456789",
    customerEmail: "nasrin.akter@example.com",
    customerTotalBookings: 7,
    groundId: "GR-03",
    groundName: "Red Court",
    groundType: "badminton",
    groundCapacity: 4,
    groundOpeningTime: "08:00",
    groundClosingTime: "21:00",
    groundIsActive: true,
    date: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    startTime: "16:00",
    endTime: "17:00",
    duration: 1,
    pricePerHour: 900,
    amount: 900,
    status: "confirmed",
    paymentStatus: "paid",
    paymentMethod: "card",
    cardLast4: "1234",
    stripeTransactionId: "pi_3PqB2SLkdIwHu7ix1RNIBGS3",
    notes: "",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { event: "Booking created", timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString() },
      { event: "Confirmation email sent", timestamp: new Date(Date.now() - 3.95 * 60 * 60 * 1000).toISOString() },
      { event: "Payment completed", timestamp: new Date(Date.now() - 3.8 * 60 * 60 * 1000).toISOString() },
      { event: "Booking confirmed", timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString() },
    ],
  },
  "BK-004": {
    id: "BK-004",
    customerId: "CU-04",
    customerName: "Salam Sheikh",
    customerPhone: "+880 1614-567890",
    customerEmail: "salam.sheikh@example.com",
    customerTotalBookings: 21,
    groundId: "GR-01",
    groundName: "Green Arena",
    groundType: "football",
    groundCapacity: 22,
    groundOpeningTime: "06:00",
    groundClosingTime: "23:00",
    groundIsActive: true,
    date: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    startTime: "19:00",
    endTime: "21:00",
    duration: 2,
    pricePerHour: 1200,
    amount: 2400,
    status: "confirmed",
    paymentStatus: "paid",
    paymentMethod: "card",
    cardLast4: "9999",
    stripeTransactionId: "pi_3PqC3TLkdIwHu7ix2SOJCHT4",
    notes: "",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { event: "Booking created", timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString() },
      { event: "Confirmation email sent", timestamp: new Date(Date.now() - 5.95 * 60 * 60 * 1000).toISOString() },
      { event: "Payment completed", timestamp: new Date(Date.now() - 5.7 * 60 * 60 * 1000).toISOString() },
      { event: "Booking confirmed", timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString() },
    ],
  },
  "BK-005": {
    id: "BK-005",
    customerId: "CU-05",
    customerName: "Farida Begum",
    customerPhone: "+880 1515-678901",
    customerEmail: "farida.begum@example.com",
    customerTotalBookings: 5,
    groundId: "GR-04",
    groundName: "Gold Tennis",
    groundType: "tennis",
    groundCapacity: 4,
    groundOpeningTime: "06:00",
    groundClosingTime: "22:00",
    groundIsActive: true,
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    startTime: "08:00",
    endTime: "09:00",
    duration: 1,
    pricePerHour: 900,
    amount: 900,
    status: "cancelled",
    paymentStatus: "refunded",
    paymentMethod: "card",
    cardLast4: "5566",
    stripeTransactionId: "pi_3PqD4ULkdIwHu7ix3TPKDIU5",
    notes: "Customer cancelled",
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { event: "Booking created", timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString() },
      { event: "Confirmation email sent", timestamp: new Date(Date.now() - 9.95 * 60 * 60 * 1000).toISOString() },
      { event: "Payment completed", timestamp: new Date(Date.now() - 9.7 * 60 * 60 * 1000).toISOString() },
      { event: "Booking confirmed", timestamp: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString() },
      { event: "Booking cancelled & refund issued", timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString() },
    ],
  },
  "BK-006": {
    id: "BK-006",
    customerId: "CU-06",
    customerName: "Jahangir Alam",
    customerPhone: "+880 1716-789012",
    customerEmail: "jahangir.alam@example.com",
    customerTotalBookings: 9,
    groundId: "GR-02",
    groundName: "Blue Pitch",
    groundType: "cricket",
    groundCapacity: 30,
    groundOpeningTime: "07:00",
    groundClosingTime: "22:00",
    groundIsActive: true,
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    startTime: "14:00",
    endTime: "16:00",
    duration: 2,
    pricePerHour: 1800,
    amount: 3600,
    status: "completed",
    paymentStatus: "paid",
    paymentMethod: "card",
    cardLast4: "3344",
    stripeTransactionId: "pi_3PqE5VLkdIwHu7ix4UQLEJV6",
    notes: "",
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    timeline: [
      { event: "Booking created", timestamp: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString() },
      { event: "Confirmation email sent", timestamp: new Date(Date.now() - 35.9 * 60 * 60 * 1000).toISOString() },
      { event: "Payment completed", timestamp: new Date(Date.now() - 35.5 * 60 * 60 * 1000).toISOString() },
      { event: "Booking confirmed", timestamp: new Date(Date.now() - 35 * 60 * 60 * 1000).toISOString() },
      { event: "Session completed", timestamp: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString() },
    ],
  },
};

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const booking = details[id];
  if (!booking) {
    return NextResponse.json({ success: false, error: "Booking not found" }, { status: 404 });
  }
  return NextResponse.json({ success: true, data: booking });
}
